### ISSUE TITLE
An error occurred while YARD/MismatchName cop was inspecting foo.rb

### ISSUE THREAD

**Issue by renatolond** [ksss/rubocop-yard#10]
Hi! Thanks for your work in rubocop-yard!

I got the following issue when the param definition has a syntax error:

```
Scanning foo.rb
An error occurred while YARD/MismatchName cop was inspecting foo.rb:5:0.
nil can't be coerced into Integer
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-yard-0.5.0/lib/rubocop/cop/yard/mismatch_name.rb:67:in `+'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-yard-0.5.0/lib/rubocop/cop/yard/mismatch_name.rb:67:in `add_offense_to_tag'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-yard-0.5.0/lib/rubocop/cop/yard/mismatch_name.rb:49:in `block in on_def'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-yard-0.5.0/lib/rubocop/cop/yard/mismatch_name.rb:31:in `each'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-yard-0.5.0/lib/rubocop/cop/yard/mismatch_name.rb:31:in `each_with_index'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-yard-0.5.0/lib/rubocop/cop/yard/mismatch_name.rb:31:in `on_def'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/commissioner.rb:107:in `public_send'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/commissioner.rb:107:in `block (2 levels) in trigger_responding_cops'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/commissioner.rb:106:in `block in trigger_responding_cops'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/commissioner.rb:105:in `each'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/commissioner.rb:105:in `trigger_responding_cops'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/commissioner.rb:69:in `on_def'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-ast-1.29.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cop/team.rb:98:in `investigate'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:345:in `block in inspect_file'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:344:in `each'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:344:in `flat_map'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:344:in `inspect_file'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:314:in `loop'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:164:in `block in file_offenses'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:189:in `file_offense_cache'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:163:in `file_offenses'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:154:in `process_file'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:134:in `each'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:134:in `reduce'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:134:in `each_inspected_file'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:120:in `inspect_files'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/runner.rb:73:in `run'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli/command.rb:11:in `run'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli/environment.rb:18:in `run'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli.rb:118:in `run_command'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli.rb:125:in `execute_runners'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli.rb:51:in `block in run'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli.rb:77:in `profile_if_needed'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/lib/rubocop/cli.rb:43:in `run'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/exe/rubocop:19:in `block in <top (required)>'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/lib/ruby/gems/3.2.0/gems/rubocop-1.56.3/exe/rubocop:19:in `<top (required)>'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/bin/rubocop:25:in `load'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/bin/rubocop:25:in `<main>'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/bin/ruby_executable_hooks:22:in `eval'
/home/renatolond/.rvm/rubies/ruby-3.2.2-jemalloc/bin/ruby_executable_hooks:22:in `<main>'
C

Offenses:

foo.rb:3:11: C: YARD/TagTypeSyntax: (SyntaxError) expecting END, got name 'Object'
# @param [Hash<Symbol=>Object] config Hash containing optional configuration
          ^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected

1 error occurred:
An error occurred while YARD/MismatchName cop was inspecting foo.rb:5:0.
```

Here's the file that caused the issue
```
# frozen_string_literal: true

# @param [Hash<Symbol=>Object] config Hash containing optional configuration
# @return [void]
def my_func(config)
  config
end
```

**Comment by ksss** [comment]
@renatolond Thank you for your reporting.
I fixed it!
