### ISSUE TITLE
Error with invalid param name

### ISSUE THREAD

**Issue by frsantos** [ksss/rubocop-yard#18]
The cop `YARD/MismatchName` fails if the param name has a wrong format.

```ruby
class Test
  # @param [Hash] context, Extra colon at the end of param name.
  def test(context)
  end
end
```

It fails with:

```txt
An error occurred while YARD/MismatchName cop was inspecting /app/test.rb:3:2.
nil can't be coerced into Integer
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:153:in `+'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:153:in `add_offense_to_tag'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:67:in `block (2 levels) in on_def'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:41:in `each'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:41:in `each_with_index'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:41:in `block in on_def'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:138:in `block in each_tags_by_docstring'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:137:in `each'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:137:in `each_tags_by_docstring'
/usr/local/bundle/gems/rubocop-yard-0.8.1/lib/rubocop/cop/yard/mismatch_name.rb:40:in `on_def'
```

**Comment by ksss** [comment]
@frsantos Thank you for reporting.
I fixed by v0.8.2.
